CREATE TABLE IF NOT EXISTS INVOICE (
    ID 		VARCHAR(36),
    TOTAL 	DECIMAL(18,2),
    PRIMARY KEY ( ID )
);


CREATE TABLE IF NOT EXISTS DETAIL_LINE (
    ID 			VARCHAR(36),
    PRODUCT 	VARCHAR(200),
    AMOUNT 		DECIMAL(9,0),
    PRICE 		DECIMAL(18,2),
    INVOICE_ID	VARCHAR(36),
    PRIMARY KEY ( ID ),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID)
);
